version: '3'
services:

  # basic infrastructure
  config-server:
    container_name: example-config-server
    image: 'amoraes/spring-cloud-ecs-example-config-server:latest'
    network_mode: bridge
    ports:
    - '8888:8888'
    environment:
    - LOCAL_DOCKER_ENV=true
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTIONS=-Xmx128m
    - HOST_DOMAIN=localhost.local.com
    - server.port=8888

  eureka:
    container_name: example-eureka
    image: 'amoraes/spring-cloud-ecs-example-eureka:latest'
    network_mode: bridge
    ports:
    - '8761:8761'
    depends_on:
    - config-server
    environment:
    - LOCAL_DOCKER_ENV=true
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTIONS=-Xmx128m
    - HOST_DOMAIN=localhost.local.com
    - server.port=8761
    - spring.cloud.config.uri=http://localhost.local.com:8888

  gateway:
    container_name: example-gateway
    image: 'amoraes/spring-cloud-ecs-example-gateway:latest'
    network_mode: bridge
    ports:
    - '9090:9090'
    depends_on:
    - eureka
    environment:
    - LOCAL_DOCKER_ENV=true
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTIONS=-Xmx256m
    - HOST_DOMAIN=localhost.local.com
    - server.port=9090
    - spring.cloud.config.uri=http://localhost.local.com:8888

  spring-boot-admin:
    container_name: example-spring-boot-admin
    image: 'amoraes/spring-cloud-ecs-example-spring-boot-admin:latest'
    network_mode: bridge
    ports:
    - '9001:9001'
    depends_on:
    - eureka
    environment:
    - LOCAL_DOCKER_ENV=true
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTIONS=-Xmx128m
    - HOST_DOMAIN=localhost.local.com
    - server.port=9001
    - spring.cloud.config.uri=http://localhost.local.com:8888


