Description: ECS task and service for Zipkin


Parameters:

  VPC:
    Type: 'AWS::EC2::VPC::Id'

  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet::Id'

  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet::Id'

Resources:

  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: example-zipkin
      NetworkMode: 'awsvpc'
      ContainerDefinitions:
      - Name: zipkin
        Essential: 'true'
        Image: openzipkin/zipkin
        Memory: 500
        HealthCheck:
          Command: [ 'CMD-SHELL', 'curl -f http://localhost:9411/actuator/health | grep UP || exit 1' ]
          Interval: 10
          Retries: 3
          StartPeriod: 60
          Timeout: 5
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !ImportValue ExampleECSClusterCloudWatchLogGroup
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: zipkin
        PortMappings:
        - ContainerPort: 9411
          HostPort: 9411

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !ImportValue ExampleECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref Task
      HealthCheckGracePeriodSeconds: 30
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!ImportValue ExampleECSClusterAllowInternalSecurityGroup]
          Subnets: [!Ref PrivateSubnet1, !Ref PrivateSubnet2]
      LoadBalancers:
      - ContainerName: zipkin
        ContainerPort: 9411
        TargetGroupArn: !Ref TargetGroup
      ServiceRegistries:
      - RegistryArn: !GetAtt ServiceDiscoveryService.Arn

  ServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: 'Discovery by private DNS for Zipkin'
      DnsConfig:
        DnsRecords:
        - Type: A
          TTL: 60
        NamespaceId: !ImportValue ExampleECSClusterVPCPrivateDNSNamespace
      HealthCheckCustomConfig:
        FailureThreshold: '1'
      Name: zipkin

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      HealthCheckPath: /actuator/health
      Port: 9411
      Protocol: HTTP
      VpcId: !Ref VPC

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: TargetGroup
      Conditions:
      - Field: path-pattern
        Values:
        - /zipkin*
      ListenerArn: !ImportValue ExampleECSClusterInternalALBHttpListernArn
      Priority: 50